on:
  pull_request:
    branches:
      - master
name: linters & tests
jobs:
  linters:
    name: linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run eslint
      - run: npm run stylelint
      - run: npm run svelte:check
  tests:
    name: unit and integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: cp template.env .env
      - run: npm ci
      - run: npm run fontello
      - run: npm run build
      - run: npm run test:headless:prod
